# Generated by Django 4.2.7 on 2023-11-18 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "policy_when_on_holiday",
                    models.CharField(
                        choices=[
                            ("FIND_OTHER", "Try to find another assignee"),
                            ("WHEN_BACK", "Give to first assignee when back"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "policy_overdue_inflation",
                    models.FloatField(
                        default=0.05,
                        help_text="Multiplier applied to job if grabbed after due date",
                    ),
                ),
                (
                    "policy_max_team_diff",
                    models.PositiveSmallIntegerField(
                        default=600,
                        help_text="Maximum relative credit in team to consider for job assigner",
                    ),
                ),
                (
                    "policy_max_job_diff",
                    models.PositiveSmallIntegerField(
                        default=120,
                        help_text="Maximum relative credit on a job to consider for job assigner",
                    ),
                ),
                (
                    "policy_team_credit_weight",
                    models.PositiveSmallIntegerField(
                        help_text="Weight given to relative credit within the team"
                    ),
                ),
                (
                    "policy_job_credit_weight",
                    models.PositiveSmallIntegerField(
                        help_text="Weight given to relative credit on each job"
                    ),
                ),
                (
                    "policy_random_weight",
                    models.PositiveSmallIntegerField(help_text="Random weighting"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("Member", "Member"), ("Admin", "Admin")],
                        max_length=10,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="teams.team",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=512)),
                (
                    "role",
                    models.CharField(
                        choices=[("Member", "Member"), ("Admin", "Admin")],
                        max_length=10,
                    ),
                ),
                ("expires", models.DateTimeField()),
                ("declined", models.BooleanField(blank=True, null=True)),
                ("blocked", models.BooleanField(blank=True, null=True)),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teams.team"
                    ),
                ),
            ],
        ),
    ]
