# Generated by Django 4.2.7 on 2023-11-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="blocked",
            field=models.BooleanField(default=False),
        ),
    ]
