---
- name: Copy artifact to remote server
  hosts: all
  vars:
    deploy_root: /opt/housework/

  tasks:
    - name: Copy artifact to remote server
      copy:
        src: "housework-app/build/"
        dest: "{{ deploy_root }}/app"
      become: yes


