---
- name: Copy artifact to remote server
  hosts: all
  vars:
    deploy_root: /opt/housework/

  tasks:
    - name: Copy artifact to remote server
      copy:
        src: "housework-app/build/"
        dest: "{{ deploy_root }}/app"
      become: yes

  environment:
    ANSIBLE_HOST_KEY_CHECKING: False
    ANSIBLE_PRIVATE_KEY_FILE: "{{ lookup('env','TDNSH_DEPLOY_PRIVATE_KEY') }}"

