"""
Django settings for hwk project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from hwk.environment import HwkEnviron

_environ = HwkEnviron(_env_file='../.env')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _environ.hwk_django_secret_key

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _environ.hwk_sec_django_debug

ALLOWED_HOSTS = _environ.hwk_sec_allowed_hosts


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "hwk.apps.api",
    "hwk.apps.jobs",
    "hwk.apps.people",
    "hwk.apps.teams",
    "hwk.apps.notifications",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "hwk.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "hwk.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
AUTH_USER_MODEL = "people.HwkUser"

CORS_ALLOWED_ORIGINS = _environ.hwk_sec_cors_origins

CORS_ALLOW_METHODS = ["DELETE", "GET", "OPTIONS", "PATCH", "POST", "PUT"]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-sessionid",
]

CSRF_TRUSTED_ORIGINS = _environ.hwk_sec_csrf_trusted

CORS_ALLOW_CREDENTIALS = True


# Celery Configuration Options
CELERY_TIMEZONE = "Europe/London"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

CELERY_BROKER_URL = _environ.hwk_celery_broker_url


EMAIL_BACKEND = _environ.hwk_smtp_email_backend
EMAIL_HOST = _environ.hwk_smtp_email_host
EMAIL_USE_TLS = _environ.hwk_smtp_email_use_tls
EMAIL_PORT = _environ.hwk_smtp_email_port
EMAIL_USE_SSL = _environ.hwk_smtp_email_use_ssl
EMAIL_HOST_USER = _environ.hwk_smtp_email_host_user
EMAIL_HOST_PASSWORD = _environ.hwk_smtp_email_host_password

WEBPUSH_VAPID_PRIVATE = _environ.hwk_webpush_vapid_private
WEBPUSH_VAPID_PUBLIC = _environ.hwk_webpush_vapid_public

SECURE_HSTS_SECONDS = 60 * 60 if _environ.hwk_sec_is_prod else 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = _environ.hwk_sec_is_prod
SECURE_HSTS_PRELOAD = _environ.hwk_sec_is_prod

SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = _environ.hwk_sec_is_prod
CSRF_COOKIE_SECURE = _environ.hwk_sec_is_prod
