# Generated by Django 4.2.7 on 2023-11-11 14:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('default_credit', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_priority', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Open', 'Open'), ('Overdue', 'Overdue'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('default_credit', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('open_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('failed_days', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('credit', models.PositiveSmallIntegerField()),
                ('job_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='jobs.jobconfig')),
            ],
        ),
        migrations.CreateModel(
            name='JobTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lifecycle', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Open', 'Open'), ('Overdue', 'Overdue'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], max_length=50)),
                ('urgent', models.BooleanField(default=False)),
                ('create_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_create', to='jobs.jobconfig')),
                ('from_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trigger_from', to='jobs.jobconfig')),
            ],
        ),
        migrations.CreateModel(
            name='JobScheduleRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('DayInWeek', 'Day in Week'), ('DaysSince', 'Days Since'), ('DayInYear', 'Day in Year')], max_length=10)),
                ('params', models.JSONField()),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobtrigger')),
            ],
        ),
    ]
