# Generated by Django 4.2.7 on 2023-11-18 10:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.TextField(max_length=128)),
                ("title", models.CharField(max_length=256)),
                ("body", models.TextField()),
                ("date_read", models.DateTimeField(blank=True, null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubscriptionChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "channel_type",
                    models.CharField(
                        choices=[("BRW_PSH", "Browser push notification")], max_length=8
                    ),
                ),
                ("config", models.JSONField()),
                ("enabled", models.BooleanField(default=True)),
            ],
        ),
    ]
