name: Build and Deploy

on:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  dev-build-and-push-docker:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./housework-api
        push: true
        tags: tomnewport/housework:development

  dev-build-cra-app:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        cd housework-app
        npm install

    - name: Build CRA app
      run: |
        cd housework-app
        npm run build
      env:
        PUBLIC_URL: ${{ vars.PUBLIC_URL }}
        REACT_APP_HOUSEWORK_API_ROOT: ${{ vars.REACT_APP_HOUSEWORK_API_ROOT }}
        REACT_APP_VAPID_PUBLIC_KEY: ${{ vars.REACT_APP_VAPID_PUBLIC_KEY }}

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-directory
        path: housework-app/build/

  dev-deploy-development:
    runs-on: ubuntu-latest
    environment: development
    needs:
    - dev-build-and-push-docker
    - dev-build-cra-app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: build-directory
          path: deploy/housework-app/build/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.TDNSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa tdn.sh >> ~/.ssh/known_hosts
        env:
          TDNSH_KEY: ${{ secrets.TDNSH_KEY }}

      - name: Run Ansible Playbook
        run: ansible-playbook -i deploy/hosts.ini deploy/deploy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
          APP_CONFIG: ${{ secrets.APP_CONFIG }}
          APP_DOMAIN: ${{ vars.APP_DOMAIN }}
