name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./housework-api
        push: true
        tags: tomnewport/housework:latest

  build-cra-app:
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd housework-app
        npm install

    - name: Build CRA app
      run: |
        cd housework-app
        npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-directory
        path: housework-app/build/

